[package]
name    = "xkb"
version = "0.2.0"

authors = ["meh. <meh@schizofreni.co>"]
license = "WTFPL"

description = "Rusty wrapper around libxkbcommon."
repository  = "https://github.com/meh/rust-xkb"
keywords    = ["xkb", "xkbcommon", "x11", "xcb"]

[dependencies]
bitflags      = "0.9"
libc          = "0.2"
xkbcommon-sys = "0.7"

[dependencies.xcb]
version  = "0.8"
features = ["xkb"]
optional = true

[features]
static = ["xkbcommon-sys/static"]
x11    = ["xkbcommon-sys/x11", "xcb"]
